#' @title Import Metrics From MarkDuplicates
#'
#' @description Imports metrics files as generated by MarkDuplicates
#'
#' @details Files generated by MarkDuplicates from the picard set of tools can
#' be imported using this functions.
#' Files must be exactly as generated by this tool, without modification.
#'
#' @param x \code{character}. Vector of filenames
#' @param useBasename \code{logical} Strip file paths from the LIBRARY column
#' in the returned tibbles?
#'
#' @return A list with two tibbles.
#' The first (\code{$metrics}) is the metrics for each file, with the second
#' (\code{$histogram}) being the histogram for each file.
#'
#' @examples
#' sysDir <- system.file("extdata", package = "ngsReports")
#' fl <- list.files(sysDir, "Dedup_metrics.txt", full.names = TRUE)
#' dupMetrics <- importDuplicationMetrics(fl)
#'
#' @export
importDuplicationMetrics <- function(x, useBasename = TRUE){

    ## Exit if all files don't exist & let the user get their paths right
    fExists <- file.exists(x)
    if (!all(fExists)) stop(paste("Couldn't find", x[!fExists]))

    ## Read the data & check the structure
    data <- lapply(x, readLines)
    allValid <- vapply(data, .isValidDuplicationMetrics, logical(1))
    if (!all(allValid)) stop(
        paste("File", x[!allValid], "has an incorrect structure")
    )

    ## Define a function to return basename or not in the below functions
    filePathFun <- function(){
        if (useBasename) return(basename)
        else return(c)
    }


    ## Collect the metrics from all files as a tibble
    metrics <- lapply(data, function(x){
        ## Find the library name
        libName <- grep(
            "picard.sam.markduplicates.MarkDuplicates.+INPUT=", x, value = TRUE
        )
        libName <- gsub(".+INPUT=\\[(.+)\\] OUTPUT.+", "\\1", libName[[1]])
        ## Find the header. The next two rows will be the colnames + data
        metHeader <- grep("METRICS CLASS\tpicard.sam.DuplicationMetrics", x)
        df <- .splitByTab(x[seq(metHeader + 1, by = 1, length.out = 2)])
        df$LIBRARY <- filePathFun()(libName)
        df
    })
    metrics <- dplyr::bind_rows(metrics)
    ## Now ensure the correct types
    metrics$PERCENT_DUPLICATION <- as.numeric(metrics$PERCENT_DUPLICATION)
    intCols <- setdiff(colnames(metrics), c("LIBRARY", "PERCENT_DUPLICATION"))
    metrics[intCols] <- lapply(metrics[intCols], as.integer)
    metrics <- as_tibble(metrics)

    ## Collect the histogram data from all files as a tibble
    histData <- lapply(data, function(x){
        ## Find the library name
        libName <- grep(
            "picard.sam.markduplicates.MarkDuplicates.+INPUT=", x, value = TRUE
            )
        libName <- gsub(".+INPUT=\\[(.+)\\] OUTPUT.+", "\\1", libName[[1]])

        ## Find the header then remove up until that line
        histHeader <- grep("HISTOGRAM\tjava.lang.Double", x)
        x <- x[-seq_len(histHeader)]
        ## Remove any blank lines (this is the last line)
        x <- x[!grepl("^$", x)]
        df <- .splitByTab(x)
        df$LIBRARY <- filePathFun()(libName)
        dplyr::select(df, "LIBRARY", tidyselect::everything())
    })
    histData <- dplyr::bind_rows(histData)
    ## Ensure the correct types
    histData$BIN <- as.integer(histData$BIN)
    histData$VALUE <- as.numeric(histData$VALUE)
    histData <- as_tibble(histData)

    ## Setup the output, then format the column names
    out <- list(metrics = metrics, histogram = histData)
    lapply(out, function(x){
        colnames(x) <- stringr::str_replace_all(colnames(x), "_", " ")
        colnames(x) <- stringr::str_to_title(colnames(x))
        x
    })
}

#' @title Check for a valid Duplication Metrics log
#' @description Checks internal structure of the parsed log file
#' @param x Character vector containing parsed log file using the function
#' readLines
#' @return logical(1)
#' @keywords internal
.isValidDuplicationMetrics <- function(x){

    ## Check the METRICS CLASS data
    metricsHeader <- grep("METRICS CLASS\tpicard.sam.DuplicationMetrics", x)
    stopifnot(length(metricsHeader) == 1) # Must appear only once
    metricCols <- c("LIBRARY", "UNPAIRED_READS_EXAMINED", "READ_PAIRS_EXAMINED",
                    "SECONDARY_OR_SUPPLEMENTARY_RDS", "UNMAPPED_READS",
                    "UNPAIRED_READ_DUPLICATES", "READ_PAIR_DUPLICATES",
                    "READ_PAIR_OPTICAL_DUPLICATES", "PERCENT_DUPLICATION",
                    "ESTIMATED_LIBRARY_SIZE")
    ## Check the column names in the log match the expected columns
    checkMetCols <- all(names(.splitByTab(x[metricsHeader + 1])) == metricCols)

    ## Check the HISTOGRAM data
    histHeader <- grep("HISTOGRAM\tjava.lang.Double", x)
    stopifnot(length(histHeader) == 1) # Must appear only once
    histCols <- c("BIN", "VALUE")
    checkHistCols <- all(names(.splitByTab(x[histHeader + 1])) == histCols)

    all(checkMetCols, checkHistCols)
}
