#' @title Import STAR log files
#'
#' @description Imports \code{Log.final.out} files generated by STAR
#'
#' @details Imports one or more \code{Log.final.out} files as output by the
#' aligner STAR.
#' Values which are simple to calculate from the returned information are
#' returned as proportions intead of percentages.
#' Indel and substitution rates are left as character values showing
#' percentages.
#'
#' @param x \code{character}. Vector of filenames
#' @param useBasename \code{logical} Strip file paths from the Filename column
#' in the returned tibbles?
#'
#' @return A \code{tibble}.
#' Column names are broadly similar to those in the supplied files,
#' but have been modified for easier handling under R naming conventions.
#'
#' In addition, the columns \code{Mapping_Duration} and the overall
#' \code{Total_Mapped_Percent} are returned
#'
#' @examples
#' starLog <- system.file("extdata", "log.final.out", package = "ngsReports")
#' df <- importStarLogs(starLog)
#'
#' @importFrom lubridate parse_date_time
#'
#' @export
importStarLogs <- function(x, useBasename = TRUE){

    ## Exit if all files don't exist & let the user get their paths right
    fExists <- file.exists(x)
    if (!all(fExists)) stop(paste("Couldn't find", x[!fExists]))

    ## Read the data & check the structure
    ln <- lapply(x, readLines)
    validLogs <- vapply(ln, .isValidStarLog, logical(1))
    if (any(!validLogs)) stop("Incorrect file structure for:", x[!validLogs])

    ## Reformat as a data.frame / tibble
    df <- lapply(ln, function(x){
        ## Split on '|\t'
        x <- stringr::str_split_fixed(x, pattern = "\\|\t", n = 2)
        ## Remove whitespace
        x <- apply(x, MARGIN = 2, stringr::str_trim)
        ## Remove blank rows
        x <- x[rowSums(x == "") == 0,]
        ## Tidy up the percent signs & brackets
        x[, 1] <- gsub("%", "Percent", x[,1])
        x <- apply(x, 2, stringr::str_remove_all, "[%\\(\\)]")
        ## Define the column names
        cols <- stringr::str_to_title(x[,1])
        cols <- gsub("[ :,]+", "_", cols)
        cols <-
            gsub("([ACGTacgt]{2}/[ACGTacgt]{2})", "\\U\\1", cols, perl = TRUE)
        ## Form a list then tibble
        out <- as.list(x[,2])
        names(out) <- cols
        as_tibble(out)
    })
    df <- dplyr::bind_rows(df)
    ## Reformat the time columns
    timeCols <- grepl("On$", names(df))
    df[timeCols] <-
        lapply(df[timeCols], parse_date_time, orders = "b! d! HMS")
    ## Reformat the integer columns
    intCols <- grepl("Number", names(df))
    df[intCols] <- lapply(df[intCols], as.integer)
    ## Set the remaining columns as numeric
    df[!intCols & !timeCols] <- lapply(df[!intCols & !timeCols], as.numeric)

    ## Add the filename & additional columns
    df$Filename <- x
    if (useBasename) df$Filename <- basename(df$Filename)
    df$Mapping_Duration <- df$Finished_On - df$Started_Mapping_On
    totMapped <-
        df$Uniquely_Mapped_Reads_Number +
        df$Number_Of_Reads_Mapped_To_Multiple_Loci
    df$Total_Mapped_Percent <- 100*totMapped / df$Number_Of_Input_Reads
    df <- dplyr::select(
        df, "Filename",
        tidyselect::starts_with("Total"),
        tidyselect::contains("Input"),
        tidyselect::contains("Mapped"),
        tidyselect::contains("Splice"),
        tidyselect::ends_with("On"),
        tidyselect::contains("Mapping"),
        tidyselect::everything()
    )

    df
}

#' @title Check for a valid Star Alignment log
#' @description Checks internal structure of the parsed log file
#' @param x Character vector containing parsed log file using the function
#' readLines
#' @return logical(1)
#' @keywords internal
.isValidStarLog <- function(x){
    ## Just check for the key fields
    chkStart <- grepl("Started job on", x[1])
    chkUniq <- any(grepl("UNIQUE READS:", x))
    chkMulti <- any(grepl("MULTI-MAPPING READS:", x))
    chkUnmapped <- any(grepl("UNMAPPED READS:", x))
    all(chkStart, chkUniq, chkMulti, chkUnmapped)
}
