#' @title Import Metrics From MarkDuplicates
#'
#' @description Imports metrics files as generated by MarkDuplicates
#'
#' @details Files generated by MarkDuplicates from the picard set of tools can be imported using this tool.
#' Files must be exactly as generated by this tool, without modification
#'
#' @param x \code{character}. Vector of filenames
#'
#' @return A list with two tibbles.
#' The first (\code{$metrics}) is the metrics for each file, with the second (\code{$histogram}) being the histogram for each file
#'
#'
#' @export
importDuplicationMetrics <- function(x){

  stopifnot(all(file.exists(x)))
  data <- lapply(x, function(fl){
    l <- readLines(fl)
    chk <- grep("METRICS CLASS\tpicard.sam.DuplicationMetrics", l)
    stopifnot(length(chk) == 1)
    # Obtain the single line df
    cols <- stringr::str_split(l[chk + 1], "\t")[[1]]
    vals <- stringr::str_split(l[chk + 2], "\t")[[1]]
    stopifnot(length(cols) == length(vals))
    names(vals) <- cols
    df <- dplyr::as_data_frame(as.list(vals))
    # Find the name of the input bam/sam file
    libName <- grep("picard.sam.markduplicates.MarkDuplicates.+INPUT=", l, value = TRUE)[1]
    libName <- gsub(".+INPUT=\\[(.+)\\] OUTPUT.+", "\\1", libName)
    df$LIBRARY <- basename(libName)
    # Get the HISTOGRAM module
    hstart <- grep("## HISTOGRAM\tjava.lang.Double", l) + 1
    h <- stringr::str_split_fixed(l[hstart + seq_len(100)], "\t", n = 2)
    colnames(h) <- stringr::str_split_fixed(l[hstart], "\t", 2)
    h <- dplyr::as_data_frame(h)
    h$BIN <- as.integer(h$BIN)
    h$VALUE <- as.numeric(h$VALUE)
    h$LIBRARY <- basename(libName)
    list(df = df, histogram = h)
  })

  df <- dplyr::bind_rows(lapply(data, function(x){x$df}))
  intCols <- setdiff(colnames(df), c("LIBRARY", "PERCENT_DUPLICATION"))
  df[intCols] <- lapply(df[intCols], as.integer)
  df$PERCENT_DUPLICATION <- as.numeric(df$PERCENT_DUPLICATION)
  histogram <- dplyr::bind_rows(lapply(data, function(x){x$histogram}))
  histogram <- dplyr::select(histogram, dplyr::one_of("LIBRARY"), dplyr::everything())
  list(metrics = df, histogram = histogram)
}
